version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-13j9cbd69zgr9"
s3_prefix = "test2"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

