AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  (SO8102) 
  add-security-headers-cff

  The CloudFront Function will add security headers to enforce https.
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    Tags:
      Publisher: AWS

Resources:
  AddSecurityHeaderFunction:
    Type: AWS::CloudFront::Function
    Properties: 
      AutoPublish: false
      FunctionConfig:
        Comment: add-security-headers-cff
        Runtime: cloudfront-js-1.0      
      FunctionCode: |
        function handler(event) {
            var response = event.response;
            var headers = response.headers;

            headers['strict-transport-security'] = { value: 'max-age=63072000; includeSubdomains; preload'}; 
            headers['content-security-policy'] = { value: "default-src 'none'; img-src 'self'; script-src 'self'; style-src 'self'; object-src 'none'"}; 
            headers['x-content-type-options'] = { value: 'nosniff'}; 
            headers['x-frame-options'] = {value: 'DENY'}; 
            headers['x-xss-protection'] = {value: '1; mode=block'}; 
            
            return response;
        }
      Name: add-security-headers-cff


Outputs:
  SolutionId:
    Description: "Solution id"
    Value: "SO8102"
